name: CI - Code Quality and Tests

on:
  push:
    branches: [ main, develop, azure-sdk-migration-ng ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        
    - name: Check code formatting with Black
      run: |
        black --check --line-length 120 .
      continue-on-error: false
        
    - name: Check import sorting with isort
      run: |
        isort --check-only --profile black .
      continue-on-error: false
        
    - name: Run Flake8 (PEP8 style check)
      run: |
        flake8 --config=.flake8 .
      continue-on-error: false
        
    - name: Run Pylint (code quality check)
      run: |
        pylint --rcfile=pylintrc aks_diagnostics/ aks-net-diagnostics.py
      continue-on-error: true  # Don't fail on pylint warnings, but show them
        
    - name: Run tests with pytest
      run: |
        pytest -v --cov=aks_diagnostics --cov-report=term --cov-report=xml
        
    - name: Upload coverage to Codecov (optional)
      if: github.event_name == 'push'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      continue-on-error: true
        
    - name: Summary
      if: always()
      run: |
        echo "## Quality Check Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Code formatting checked" >> $GITHUB_STEP_SUMMARY
        echo "✅ Import sorting checked" >> $GITHUB_STEP_SUMMARY
        echo "✅ PEP8 style checked" >> $GITHUB_STEP_SUMMARY
        echo "✅ Code quality analyzed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Tests executed" >> $GITHUB_STEP_SUMMARY
